name: Build and Release APK

on:
  workflow_dispatch: # Ручной запуск

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5
      
      - name: set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      # Шаг генерации официального цифрового ключа (Keystore)
      - name: Generate Signing Key
        run: |
          keytool -genkey -v -keystore my-release-key.jks -keyalg RSA -keysize 2048 -validity 10000 \
            -alias my-key-alias -storepass my_secret_password -keypass my_secret_password \
            -dname "CN=MaxForwarder, OU=Development, O=MaxOrg, L=Perm, S=PermKrai, C=RU"

      # Сборка и автоматическое подписание APK
      - name: Build and Sign Release APK
        run: |
          gradle assembleDebug -PbuildNumber=${{ github.run_number }}
          # Подписываем созданный APK с помощью утилиты apksigner из Android SDK
          $ANDROID_HOME/build-tools/34.0.0/apksigner sign --ks my-release-key.jks \
            --ks-pass pass:my_secret_password \
            --key-pass pass:my_secret_password \
            app/build/outputs/apk/debug/*.apk

      # Публикация подписанного APK в релизы
      - name: Create Release and Upload APK
        uses: softprops/action-gh-release@v2
        with:
          tag_name: 'v1.0.0-debug'
          name: 'Manual Build'
          draft: false
          prerelease: false
          make_latest: true
          overwrite_files: true
          files: app/build/outputs/apk/debug/*.apk
