name: Build and Release APK

on:
  workflow_dispatch: # Ручной запуск из вкладки Actions

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Права на редактирование релизов

    steps:
      - uses: actions/checkout@v5
      
      - name: set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Build Debug APK
        run: gradle assembleDebug -PbuildNumber=${{ github.run_number }}
        
      # Создание релиза с принудительной очисткой старых файлов
      - name: Create Release and Upload APK
        uses: softprops/action-gh-release@v2
        with:
          tag_name: 'v1.0.0-debug'
          name: 'Manual Build'
          draft: false
          prerelease: false
          make_latest: true
          overwrite: true # КРИТИЧЕСКИЙ ПАРАМЕТР: заставляет удалять старые ассеты с другими именами перед заливкой
          files: app/build/outputs/apk/debug/*.apk
